version: "3.8"

services:
  db:
    image: mysql:8.1.0
    env_file:
      - ./db/.env
    ports:
      - 3306:3306
    networks:
      - app-network
    volumes:
      - db_data:/var/lib/mysql

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 80:80
    networks:
      - app-network

  app:
    build:
      context: ./app
    ports:
      - 3000:3000
    env_file:
      - ./app/.env
    volumes:
      - ./app:/app
    networks:
      - app-network
    depends_on:
      - db

networks:
  app-network:
    driver: bridge

volumes:
  db_data: